# PHP project
language: php

# which versions of PHP to build with
php:
- 5.6

# set global environment variables
env:
  global:
    # make PROJECTNAME from vendor/project
    # this strips everything before the last /
    - PROJECTNAME=${TRAVIS_REPO_SLUG##*/}

# make sure we have the latest version of composer
before_install:
- composer self-update

# install dependencies
install:
- composer install

# no phpunit tests (yet)
script: true

# no email notifications
notifications:
  email: false

# before deployment make the zipfile to upload
before_deploy:
 # execute release prepare script
 - sh ./vendor/coldtrick/releases/scripts/travis/before_deploy.sh

# deployment settings
deploy:
  provider: releases
  api_key:
    secure: hDSLoLG7LG1+lG1TxWuPRZ6xtjf+dm+yvoYB5YnwmbI+WMq0UqcLztiwNF7Bu0RL3A6Ap0WbPCv1Kd9YkiR9lfK2JrPgiiPQ2h3BPkPA0YeOrEZF3a9wUTY93O/Z8hxCedNBC/EX3L/HwnM6uyOoJVGLls+E6mSetkQfaVDkMFs=
  # name of the zip to upload
  file: ${PROJECTNAME}_$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    # only when a tag is created in GitHub
    tags: true
    all_branches: true

after_deploy:
 # execute release after script
 - sh ./vendor/coldtrick/releases/scripts/travis/after_deploy.sh